# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Joks CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    needs: [ build ]

    runs-on: ubuntu-latest

    steps:
    - name: 'Deploy to Fly.io'
      uses: superfly/flyctl-actions@1.1
    - run: fly deploy
